### PR TITLE
txt value with space parsing fixed

### PR DESCRIPTION
**Pull request by architjn**
It was not parsing the values received on txt query which contains space.

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Hi @architjn 

Could you please add a test for the described scenario. 

Thanks
Stephan

**Comment by architjn** [comment]
I added my test case. But one of your test case is failing

**Comment by StephanGeorg** [comment]
The test you've added succeeded even without you're PR. 

> But one of your test case is failing

Which one?

**Comment by architjn** [comment]
1st one. Answer key is not present

**Comment by StephanGeorg** [comment]
Your PR crashes the result.

**Pull request closed without merging**
