### PR TITLE
Value of some Domains were being lost

### PR DESCRIPTION
**Pull request by mickey101**
Example if a value is as follows  
 v=spf1 ip4:192.168.0.1/16-all  
it was only returning ip4:192.168.0.1/16-all

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Thanks @mickey101.

Could you please provide test for the scenario?

**Comment by mickey101** [comment]
Working on it! will update the PR soon

**Comment by mickey101** [comment]
@StephanGeorg Have a look!

**Comment by omanizer** [comment]
Hey @StephanGeorg do you think this could get merged anytime soon? :)  Thanks for the great work.

**Comment by StephanGeorg** [comment]
Sure. Will do this today. Sry for delay.

**Comment by newerton** [comment]
@StephanGeorg Please, I need this update! :)

**Comment by mickey101** [comment]
@StephanGeorg  is there an issue with the PR?

**Comment by StephanGeorg** [comment]
Fixed in https://github.com/StephanGeorg/node-dig-dns/commit/9b25c91fca8db5427f571e3a0aee245db85fd30e

**Pull request closed without merging**
